[project]
name = 'Tokenized-Decentralized-Outdoor-Thermometer-Networks'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.accuracy-calibration]
path = 'contracts/accuracy-calibration.clar'
clarity_version = 2
epoch = 2.5

[contracts.replacement-tracking]
path = 'contracts/replacement-tracking.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
